server:
  port: 8081

spring:
  application:
    name: "social"

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3366/social
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
